# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yongze.dotalk.cn
date_format: "ordinal"
title: Yongze | Chen
subtitle: "Coding My Life..."
description: "Yongze's Tech Blog"
keywords: 陈永泽, yongze
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: yongze.chen
organization: Backend Developer
organization_url: https://yongze.dotalk.cn
github_username: chenyongze
location: Beijing, China
email: sapphire.php@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
    -
        href: /
        label: 首页

    -
        href: /categories/
        label: 分类

    -
        href: /open-source/
        label: 开源贡献

    -
        href: /about.html
        label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chenyongze/chenyongze.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: disqus

# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: chenyongze

# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 
    repo: 
    clientID: 
    clientSecret: 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-112980446-1
